set(ELLIPTIC_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/core/elliptic)

set(ELLIPTIC_SOURCES
        ${ELLIPTIC_SOURCE_DIR}/elliptic.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticWorkspace.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticApplyMask.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticUpdateJacobi.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticBuildMultigridLevelKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticOperator.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticPreconditioner.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticPreconditionerSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/ellipticSolutionProjection.cpp
        ${ELLIPTIC_SOURCE_DIR}/SEMFEMSolver.cpp
        ${ELLIPTIC_SOURCE_DIR}/SEMFEMSolverBuild.cpp
        ${ELLIPTIC_SOURCE_DIR}/registerEllipticKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/registerEllipticPreconditionerKernels.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticBuildMultigridLevelFine.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticBuildMultigridLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticMultiGridUpdateLambda.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/optimalCoeffs.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/determineMGLevels.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticParseMultigridSchedule.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticMultiGridLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticMultiGridLevelSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticMultiGridSchwarz.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticMultiGridSetup.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/ellipticBuildFEM.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/level.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/MGSolver.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/coarseLevel.cpp
        ${ELLIPTIC_SOURCE_DIR}/MG/fdm/benchmark.cpp
        ${ELLIPTIC_SOURCE_DIR}/axHelm/benchmark.cpp
)

set(ELLIPTIC_INCLUDE
    ${ELLIPTIC_SOURCE_DIR}
    PRIVATE
    ${ELLIPTIC_SOURCE_DIR}/axHelm
    ${ELLIPTIC_SOURCE_DIR}/MG/fdm
    ${ELLIPTIC_SOURCE_DIR}/MG
)
