#!/usr/bin/env bash
# ============================================================================
# rebuild_mana_aurora.sh – Rebuild MANA with correct Aurora Makefile_config
#
# ROOT CAUSE: MANA was built with the generic (non-Aurora) Makefile_config,
# which uses:
#   MPICXX = mpic++ -std=c++14  (wrong, Aurora uses mpicxx)
#   MPI_LD_FLAG = -L$HOME/mpich-static/usr/lib64 -lmpi ...  (doesn't exist)
#
# This script:
#   1. Patches Makefile_config for Aurora (Cray MPICH 5.0 + Intel oneAPI)
#   2. Cleans and rebuilds MANA
#   3. Verifies the build
#   4. Runs a quick MANA test
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

MANA_ROOT="${MANA_ROOT:-${HOME}/.local/share/guard-agent/dmtcp-src/mana}"
INSTALL_PREFIX="${HOME}/.local"
COORD_PORT="${COORD_PORT:-7906}"
COORD_HOST="$(hostname)"

echo "============================================================"
echo "  Rebuild MANA for Aurora"
echo "============================================================"
echo ""
echo "MANA_ROOT: ${MANA_ROOT}"
echo "INSTALL_PREFIX: ${INSTALL_PREFIX}"
echo ""

if [[ ! -d "${MANA_ROOT}" ]]; then
    echo "ERROR: MANA source not found at ${MANA_ROOT}" >&2
    exit 1
fi

cd "${MANA_ROOT}"

# ── Step 1: Get MPI link flags from the Cray compiler wrapper ─────────────
echo "=== Step 1: Detect MPI configuration ==="
echo ""

MPI_LINK_FLAGS=""
if command -v mpicxx &>/dev/null; then
    MPI_LINK_FLAGS="$(mpicxx --cray-print-opts=libs 2>/dev/null || true)"
    echo "mpicxx --cray-print-opts=libs: ${MPI_LINK_FLAGS}"
fi

if [[ -z "${MPI_LINK_FLAGS}" ]]; then
    # Fallback: find libmpi.so and construct flags
    MPI_LIB_DIR=""
    if [[ -n "${CRAY_MPICH_DIR:-}" ]]; then
        MPI_LIB_DIR="${CRAY_MPICH_DIR}/lib"
    else
        MPI_LIB_DIR="$(dirname "$(ldd /usr/bin/mpicc 2>/dev/null | grep libmpi | awk '{print $3}')" 2>/dev/null || true)"
    fi
    if [[ -n "${MPI_LIB_DIR}" ]]; then
        MPI_LINK_FLAGS="-L${MPI_LIB_DIR} -lmpi"
    else
        MPI_LINK_FLAGS="-lmpi"
    fi
    echo "Fallback MPI_LINK_FLAGS: ${MPI_LINK_FLAGS}"
fi
echo ""

# ── Step 2: Write Aurora Makefile_config ──────────────────────────────────
echo "=== Step 2: Write Aurora Makefile_config ==="
echo ""

MAKEFILE_CONFIG="mpi-proxy-split/Makefile_config"

# Backup the original
if [[ -f "${MAKEFILE_CONFIG}" ]]; then
    cp -v "${MAKEFILE_CONFIG}" "${MAKEFILE_CONFIG}.bak.$(date +%s)"
fi

cat > "${MAKEFILE_CONFIG}" << AURORA_EOF
# Makefile_config for ALCF Aurora
# Generated by rebuild_mana_aurora.sh on $(date)
# Cray MPICH 5.0 + Intel oneAPI (icx/icpx)

CFLAGS = -g -O2 -std=gnu11
CXXFLAGS = -g -O2
FFLAGS = \${CXXFLAGS} -fallow-argument-mismatch

PLATFORM=\${shell echo \$\$HOST}
HOSTNAME_FULL := \$(shell hostname 2>/dev/null)

# Aurora platform detection
IS_AURORA = 1

# Aurora settings
MPICC = mpicc
MPICXX = mpicxx -std=c++14
MPIFORTRAN = mpifort
MPI_LD_FLAG = ${MPI_LINK_FLAGS}
MPIRUN = mpiexec
MPI_CFLAGS?= -g -O2 -std=gnu11 -g3 -fPIC
MPI_CXXFLAGS?= -g -O2 -g3 -fPIC
MPI_LDFLAGS?=
AURORA_EOF

echo "Written ${MAKEFILE_CONFIG}:"
cat "${MAKEFILE_CONFIG}"
echo ""

# ── Step 3: Re-apply source patches ──────────────────────────────────────
echo "=== Step 3: Re-apply source patches ==="
echo ""

# Patch 1: NEXT_FUNC macro: &MPI_##func -> &PMPI_##func
NEXTFUNC_H="mpi-proxy-split/mpi-wrappers/mpi_nextfunc.h"
if [[ -f "${NEXTFUNC_H}" ]] && grep -q '__typeof__(&MPI_##func)' "${NEXTFUNC_H}"; then
    echo "Patching ${NEXTFUNC_H}: &MPI_##func -> &PMPI_##func"
    sed -i 's/__typeof__(&MPI_##func)/__typeof__(\&PMPI_##func)/g' "${NEXTFUNC_H}"
fi

# Patch 2: record-replay.h: &MPI_##FNC -> &PMPI_##FNC
RECORD_REPLAY_H="mpi-proxy-split/record-replay.h"
if [[ -f "${RECORD_REPLAY_H}" ]] && grep -q '&MPI_##FNC' "${RECORD_REPLAY_H}"; then
    echo "Patching ${RECORD_REPLAY_H}: &MPI_##FNC -> &PMPI_##FNC"
    sed -i 's/&MPI_##FNC/\&PMPI_##FNC/g' "${RECORD_REPLAY_H}"
fi

# Patch 3: Direct MPI_Xxx calls in wrapper .cpp files
WRAPPERS_DIR="mpi-proxy-split/mpi-wrappers"
if [[ -d "${WRAPPERS_DIR}" ]]; then
    # Revert incorrectly-patched all-caps MANA macros
    for f in "${WRAPPERS_DIR}"/*.cpp; do
        [[ -f "$f" ]] || continue
        if grep -q 'PMPI_LOGGING' "$f"; then
            sed -i 's/PMPI_LOGGING/MPI_LOGGING/g' "$f"
        fi
    done
    # Apply correct patch
    for f in "${WRAPPERS_DIR}"/*.cpp; do
        [[ -f "$f" ]] || continue
        if grep -q '#pragma weak' "$f"; then
            sed -i -E \
                -e '/^#pragma weak/! s/([^_A-Za-z0-9])MPI_([A-Z][a-z][A-Za-z0-9_]*)\(/\1PMPI_\2(/g' \
                -e '/^#pragma weak/! s/^MPI_([A-Z][a-z][A-Za-z0-9_]*)\(/PMPI_\1(/g' \
                "$f"
        fi
    done
    echo "Patched wrapper .cpp files"
fi

# Patch 4: VLA initializer
REQ_WRAPPERS="mpi-proxy-split/mpi-wrappers/mpi_request_wrappers.cpp"
if [[ -f "${REQ_WRAPPERS}" ]] && grep -q 'was_null\[count\] = {0}' "${REQ_WRAPPERS}"; then
    echo "Patching ${REQ_WRAPPERS}: removing VLA initializer"
    sed -i 's/int was_null\[count\] = {0};/int was_null[count];/' "${REQ_WRAPPERS}"
fi

# Patch 5: PMPI_MANA_Internal compat define
MPI_WRAPPERS="mpi-proxy-split/mpi-wrappers/mpi_wrappers.cpp"
if [[ -f "${MPI_WRAPPERS}" ]] && grep -q 'MANA_Internal' "${MPI_WRAPPERS}" \
   && ! grep -q '#define PMPI_MANA_Internal' "${MPI_WRAPPERS}"; then
    echo "Patching ${MPI_WRAPPERS}: adding PMPI_MANA_Internal compat define"
    sed -i '1i\/* Clang/icpx compat: MANA_Internal has no PMPI variant */\
#define PMPI_MANA_Internal MPI_MANA_Internal' "${MPI_WRAPPERS}"
fi

# Patch 6: rex.W -> .byte 0x48
SWITCH_CTX="mpi-proxy-split/lower-half/switch-context.cpp"
if [[ -f "${SWITCH_CTX}" ]] && grep -q 'rex\.W' "${SWITCH_CTX}"; then
    echo "Patching ${SWITCH_CTX}: rex.W -> .byte 0x48"
    sed -i 's/rex\.W\\n rdfsbase/.byte 0x48; rdfsbase/g; s/rex\.W\\n wrfsbase/.byte 0x48; wrfsbase/g' "${SWITCH_CTX}"
fi

# Patch 7: void* arithmetic in copy-stack.c
COPY_STACK="mpi-proxy-split/lower-half/copy-stack.c"
if [[ -f "${COPY_STACK}" ]] && grep -q 'rc2 + dest_mem_len' "${COPY_STACK}"; then
    echo "Patching ${COPY_STACK}: void* arithmetic -> char* cast"
    sed -i 's/rc2 + dest_mem_len/(char *)rc2 + dest_mem_len/g' "${COPY_STACK}"
fi

echo ""

# ── Step 4: Clean and rebuild ─────────────────────────────────────────────
echo "=== Step 4: Clean and rebuild ==="
echo ""

# Clean previous build
make -C mpi-proxy-split clean 2>/dev/null || true
make -C mpi-proxy-split/mpi-wrappers clean 2>/dev/null || true
make -C mpi-proxy-split/lower-half clean 2>/dev/null || true

echo "Building MANA (this may take a few minutes)..."
echo ""

if make -j"$(nproc)"; then
    echo ""
    echo "✓ MANA build succeeded!"
else
    echo ""
    echo "✗ MANA build failed. Trying single-threaded..."
    if make; then
        echo "✓ MANA build succeeded (single-threaded)!"
    else
        echo "✗ MANA build failed!"
        exit 1
    fi
fi
echo ""

# Install
echo "Installing..."
make install 2>/dev/null || \
    cp -v lib/dmtcp/*.so "${INSTALL_PREFIX}/lib/dmtcp/" 2>/dev/null || \
    echo "Manual install may be needed"
echo ""

# ── Step 5: Verify the build ─────────────────────────────────────────────
echo "=== Step 5: Verify build ==="
echo ""

MANA_BIN="${MANA_ROOT}/bin"
MANA_LIB="${MANA_ROOT}/lib/dmtcp"
LOWER_HALF="${MANA_BIN}/lower-half"
LIBMANA="${MANA_LIB}/libmana.so"
LIBMPISTUB="${MANA_LIB}/libmpistub.so"

for comp in "${LIBMANA}:libmana.so" "${LOWER_HALF}:lower-half" "${LIBMPISTUB}:libmpistub.so"; do
    path="${comp%%:*}"
    name="${comp##*:}"
    if [[ -e "${path}" ]]; then
        echo "✓ ${name}: $(file "${path}" 2>/dev/null | cut -d: -f2)"
    else
        echo "✗ ${name}: MISSING"
    fi
done
echo ""

echo "lower-half ldd | grep mpi:"
ldd "${LOWER_HALF}" 2>/dev/null | grep -i mpi || echo "  (none)"
echo ""

# ── Step 6: Quick MANA test ──────────────────────────────────────────────
echo "=== Step 6: Quick MANA test ==="
echo ""

export HWLOC_COMPONENTS="-linuxio"

MANA_TEST=$(find "${MANA_ROOT}/mpi-proxy-split/test" -name "*.mana.exe" -type f 2>/dev/null | head -1)
if [[ -z "${MANA_TEST}" ]]; then
    echo "No .mana.exe test found, skipping test"
else
    echo "Test binary: ${MANA_TEST}"
    
    MANA_LAUNCH="${MANA_BIN}/mana_launch"
    MANA_START_COORD="${MANA_BIN}/mana_start_coordinator"
    DMTCP_COMMAND="${MANA_BIN}/dmtcp_command"
    CKPT_DIR="${REPO_ROOT}/build/test_mana_rebuild/ckpt"
    mkdir -p "${CKPT_DIR}"
    
    # Start coordinator
    "${DMTCP_COMMAND}" -h "${COORD_HOST}" --port "${COORD_PORT}" --quit 2>/dev/null || true
    sleep 0.5
    "${MANA_START_COORD}" --coord-port "${COORD_PORT}" --ckptdir "${CKPT_DIR}" 2>&1
    sleep 1
    
    echo ""
    echo "Running MANA test..."
    timeout 30 mpiexec -np 1 \
        "${MANA_LAUNCH}" --verbose \
        --coord-host "${COORD_HOST}" --coord-port "${COORD_PORT}" \
        --ckptdir "${CKPT_DIR}" --no-gzip \
        "${MANA_TEST}" 2>&1
    TEST_EXIT=$?
    
    echo ""
    if [[ "${TEST_EXIT}" -eq 0 ]]; then
        echo "✓ MANA test PASSED!"
    elif [[ "${TEST_EXIT}" -eq 139 ]]; then
        echo "✗ MANA test SIGSEGV (signal 11)"
    else
        echo "✗ MANA test failed (exit=${TEST_EXIT})"
    fi
    
    # Cleanup
    "${DMTCP_COMMAND}" -h "${COORD_HOST}" --port "${COORD_PORT}" --quit 2>/dev/null || true
fi

echo ""
echo "============================================================"
echo "  Rebuild complete."
echo "============================================================"
