#!/usr/bin/env bash
# ============================================================================
# rebuild_dmtcp_gcc.sh – Rebuild DMTCP with GCC on Aurora
#
# ROOT CAUSE: DMTCP was built with Intel icx compiler, which links
# libintlc.so.5 (Intel C runtime). When libdmtcp.so is LD_PRELOAD'd,
# its constructor triggers __intel_cpu_features_init_body which calls
# openat() to read /proc/cpuinfo. But DMTCP wraps openat() via
# dmtcp_openat, creating an infinite recursion loop:
#
#   libdmtcp.so constructor
#     → Intel runtime init (__intel_cpu_features_init_body)
#       → openat("/proc/cpuinfo")
#         → dmtcp_openat wrapper (in libdmtcp.so)
#           → needs Intel runtime (not yet initialized)
#             → __intel_cpu_features_init_body (again)
#               → infinite loop
#
# FIX: Rebuild DMTCP with GCC to avoid Intel runtime dependency.
# MANA must also be rebuilt since it links against DMTCP.
# ============================================================================

set -e

INSTALL_PREFIX="${HOME}/.local"
SRC_DIR="${INSTALL_PREFIX}/share/guard-agent/dmtcp-src"
DMTCP_SRC="${SRC_DIR}/dmtcp"
MANA_ROOT="${SRC_DIR}/mana"

echo "============================================================"
echo "  Rebuild DMTCP + MANA with GCC (fix Intel runtime hang)"
echo "============================================================"
echo ""

# ── Step 0: Find GCC ─────────────────────────────────────────────────
GCC_CC=""
GCC_CXX=""

# Try to find gcc/g++ in PATH
if command -v gcc >/dev/null 2>&1; then
    GCC_CC="$(which gcc)"
    GCC_CXX="$(which g++)"
elif [ -x "/usr/bin/gcc" ]; then
    GCC_CC="/usr/bin/gcc"
    GCC_CXX="/usr/bin/g++"
fi

if [ -z "${GCC_CC}" ]; then
    echo "ERROR: gcc not found in PATH or /usr/bin/"
    echo "Available compilers:"
    which cc gcc icx icpx 2>/dev/null || true
    exit 1
fi

echo "Using GCC:"
echo "  CC  = ${GCC_CC}"
echo "  CXX = ${GCC_CXX}"
echo ""

echo "GCC version:"
${GCC_CC} --version | head -1
echo ""

# Verify it's actually GCC (not a symlink to icx)
GCC_ID=$(${GCC_CC} -v 2>&1 | tail -1)
echo "Compiler ID: ${GCC_ID}"
if echo "${GCC_ID}" | grep -qi 'intel\|icx\|icc'; then
    echo "WARNING: 'gcc' appears to be Intel compiler in disguise!"
    echo "Looking for real GCC..."
    
    # On Aurora, real GCC might be in spack
    REAL_GCC=$(find /opt/aurora -name 'gcc' -path '*/bin/gcc' 2>/dev/null | head -1)
    if [ -n "${REAL_GCC}" ]; then
        GCC_CC="${REAL_GCC}"
        GCC_CXX="$(dirname ${REAL_GCC})/g++"
        echo "Found real GCC: ${GCC_CC}"
        ${GCC_CC} --version | head -1
    else
        echo "ERROR: Cannot find real GCC"
        exit 1
    fi
fi
echo ""

# ── Step 1: Clean and reconfigure DMTCP ──────────────────────────────
echo "=== Step 1: Clean and reconfigure DMTCP ==="
echo ""

cd "${DMTCP_SRC}"

echo "Cleaning previous build..."
make distclean 2>/dev/null || make clean 2>/dev/null || true

echo "Reconfiguring with GCC..."
CC="${GCC_CC}" CXX="${GCC_CXX}" ./configure --prefix="${INSTALL_PREFIX}"
echo ""

echo "Verifying Makefile uses GCC:"
grep -E '^CC |^CXX ' Makefile | head -5
echo ""

# ── Step 2: Build DMTCP ──────────────────────────────────────────────
echo "=== Step 2: Build DMTCP ==="
echo ""

make -j"$(nproc)" 2>&1 | tail -5
echo ""

echo "Verifying libdmtcp.so does NOT link Intel runtime:"
ldd lib/dmtcp/libdmtcp.so 2>/dev/null | grep -E 'intlc|svml|irng|imf' && {
    echo "ERROR: libdmtcp.so still links Intel runtime!"
    echo "Full ldd:"
    ldd lib/dmtcp/libdmtcp.so
    exit 1
} || echo "  OK - no Intel runtime dependencies"
echo ""

# ── Step 3: Install DMTCP ────────────────────────────────────────────
echo "=== Step 3: Install DMTCP ==="
echo ""

make install 2>&1 | tail -5
echo ""

echo "Installed dmtcp_launch:"
file "${INSTALL_PREFIX}/bin/dmtcp_launch" 2>/dev/null
echo ""

# ── Step 4: Rebuild MANA ─────────────────────────────────────────────
echo "=== Step 4: Rebuild MANA ==="
echo ""

cd "${MANA_ROOT}"

# MANA needs to be rebuilt against the new DMTCP
# First, ensure Makefile_config is correct for Aurora
if [ -f "mpi-proxy-split/Makefile_config" ]; then
    echo "Current Makefile_config:"
    cat mpi-proxy-split/Makefile_config
    echo ""
fi

# Get MPI link flags from Cray wrapper
MPI_LINK_FLAGS=""
if command -v mpicxx >/dev/null 2>&1; then
    MPI_LINK_FLAGS="$(mpicxx --cray-print-opts=libs 2>/dev/null || true)"
fi

# Write Aurora Makefile_config
cat > mpi-proxy-split/Makefile_config << MKEOF
# Aurora (ALCF) – Cray MPICH + Intel GPU
# Auto-generated by rebuild_dmtcp_gcc.sh
IS_AURORA = 1
MPICC  = mpicc
MPICXX = mpicxx
MPI_CFLAGS  =
MPI_LDFLAGS = ${MPI_LINK_FLAGS}
MKEOF

echo "Updated Makefile_config:"
cat mpi-proxy-split/Makefile_config
echo ""

# Apply patches for Clang/icpx compatibility (MANA is built with mpicc which uses icx)
echo "Applying MANA patches..."

# Patch 1: mpi_nextfunc.h - &MPI_##func → &PMPI_##func
NEXTFUNC_H="mpi-proxy-split/mpi-wrappers/mpi_nextfunc.h"
if [ -f "${NEXTFUNC_H}" ] && grep -q '&MPI_##func' "${NEXTFUNC_H}"; then
    sed -i 's/\&MPI_##func/\&PMPI_##func/g' "${NEXTFUNC_H}"
    echo "  Patched ${NEXTFUNC_H}"
fi

# Patch 2: record-replay.h - same fix
RR_H="mpi-proxy-split/mpi-wrappers/record-replay.h"
if [ -f "${RR_H}" ] && grep -q '&MPI_##func' "${RR_H}"; then
    sed -i 's/\&MPI_##func/\&PMPI_##func/g' "${RR_H}"
    echo "  Patched ${RR_H}"
fi

# Patch 3: wrapper .cpp files - MPI_Xxx( → PMPI_Xxx(
for WRAPPER_CPP in mpi-proxy-split/mpi-wrappers/mpi_*.cpp; do
    [ -f "${WRAPPER_CPP}" ] || continue
    if grep -qE '\bMPI_(Allreduce|Barrier|Bcast|Comm_rank|Comm_size|Finalize|Init|Recv|Send|Reduce|Gather|Scatter|Allgather|Alltoall|Wait|Test|Probe|Irecv|Isend|Ibcast|Iallreduce|Comm_dup|Comm_split|Comm_free|Cart_create|Dims_create|Type_commit|Type_free|Type_contiguous|Type_vector|Type_create_subarray|Op_create|Op_free|Abort|Get_count|Pack|Unpack|Pack_size|Wtime|Wtick|Get_processor_name|Error_string|Comm_group|Group_incl|Group_free|Intercomm_create|Comm_remote_size|Comm_test_inter|Comm_set_errhandler|Errhandler_set|Keyval_create|Keyval_free|Attr_put|Attr_get|Attr_delete|Info_create|Info_set|Info_get|Info_free|Win_create|Win_free|Win_fence|Put|Get|Accumulate|File_open|File_close|File_read|File_write|File_seek|File_get_size|File_set_size|File_delete|File_read_at|File_write_at|File_read_all|File_write_all|File_set_view|File_get_view|File_read_ordered|File_write_ordered|File_read_shared|File_write_shared|File_get_position|File_get_byte_offset)\(' "${WRAPPER_CPP}" 2>/dev/null; then
        # Only patch direct MPI_ calls that should be PMPI_ in wrapper implementations
        # Be careful not to patch string literals or comments
        :
    fi
done

# Patch 4: VLA initializer removal
for SRC_FILE in mpi-proxy-split/mpi-wrappers/*.cpp mpi-proxy-split/mpi-wrappers/*.c; do
    [ -f "${SRC_FILE}" ] || continue
    if grep -q 'int.*\[.*\] = {0}' "${SRC_FILE}" 2>/dev/null; then
        sed -i 's/\(int[[:space:]]\+[a-zA-Z_][a-zA-Z0-9_]*\[.*\]\) = {0}/\1; memset(\&\1, 0, sizeof(\1))/g' "${SRC_FILE}" 2>/dev/null
    fi
done

# Patch 5: PMPI_MANA_Internal compat define
MANA_INTERNAL_H="mpi-proxy-split/mpi-wrappers/mpi_nextfunc.h"
if [ -f "${MANA_INTERNAL_H}" ] && ! grep -q 'PMPI_MANA_Internal' "${MANA_INTERNAL_H}"; then
    sed -i '1i #define PMPI_MANA_Internal MPI_MANA_Internal' "${MANA_INTERNAL_H}"
    echo "  Added PMPI_MANA_Internal compat define"
fi

# Patch 6: switch-context.cpp rex.W → .byte 0x48
SWITCH_CTX="mpi-proxy-split/lower-half/switch-context.cpp"
if [ -f "${SWITCH_CTX}" ] && grep -q 'rex\.W' "${SWITCH_CTX}"; then
    sed -i 's/rex\.W/.byte 0x48/g' "${SWITCH_CTX}"
    echo "  Patched ${SWITCH_CTX}: rex.W → .byte 0x48"
fi

# Patch 7: copy-stack.c void* → char* cast
COPY_STACK="mpi-proxy-split/lower-half/copy-stack.c"
if [ -f "${COPY_STACK}" ] && grep -q 'void \*sp = ' "${COPY_STACK}"; then
    sed -i 's/void \*sp = /char *sp = (char*)/g' "${COPY_STACK}"
    echo "  Patched ${COPY_STACK}: void* → char*"
fi

echo ""

# Clean and rebuild MANA
echo "Cleaning MANA..."
make clean 2>/dev/null || true

echo "Building MANA..."
make -j"$(nproc)" 2>&1 | tail -10
echo ""

echo "Installing MANA..."
make install 2>&1 | tail -5
echo ""

# ── Step 5: Verify ───────────────────────────────────────────────────
echo "=== Step 5: Verification ==="
echo ""

echo "libdmtcp.so dependencies (should NOT have Intel runtime):"
ldd "${MANA_ROOT}/lib/dmtcp/libdmtcp.so" 2>/dev/null
echo ""

echo "lower-half dependencies:"
ldd "${MANA_ROOT}/bin/lower-half" 2>/dev/null | grep -E 'mpi|cray|fabric'
echo ""

echo "dmtcp_launch dependencies:"
ldd "${MANA_ROOT}/bin/dmtcp_launch" 2>/dev/null
echo ""

# ── Step 6: Quick test ───────────────────────────────────────────────
echo "=== Step 6: Quick DMTCP test ==="
echo ""

export HWLOC_COMPONENTS="-linuxio"

# Test LD_PRELOAD directly (this was the hang test)
cat > /tmp/hello_dmtcp_test.c << 'EOF'
#include <stdio.h>
#include <unistd.h>
int main() {
    printf("Hello from DMTCP test (pid=%d)\n", getpid());
    fflush(stdout);
    return 0;
}
EOF

${GCC_CC} -o /tmp/hello_dmtcp_test /tmp/hello_dmtcp_test.c 2>&1

echo "Test 1: LD_PRELOAD=libdmtcp.so hello (should NOT hang):"
timeout 5 env LD_PRELOAD="${MANA_ROOT}/lib/dmtcp/libdmtcp.so" /tmp/hello_dmtcp_test 2>&1
echo "Exit code: $?"
echo ""

echo "Test 2: dmtcp_launch /bin/echo hello:"
timeout 10 "${MANA_ROOT}/bin/dmtcp_launch" /bin/echo hello 2>&1
echo "Exit code: $?"
echo ""

echo "Test 3: dmtcp_launch hello_dmtcp_test:"
timeout 10 "${MANA_ROOT}/bin/dmtcp_launch" /tmp/hello_dmtcp_test 2>&1
echo "Exit code: $?"
echo ""

# Cleanup
rm -f /tmp/hello_dmtcp_test /tmp/hello_dmtcp_test.c

echo "============================================================"
echo "  Rebuild complete!"
echo "============================================================"
