#!/usr/bin/env bash
# ============================================================================
# rebuild_dmtcp_gcc.sh – Rebuild DMTCP with GCC on Aurora
#
# ROOT CAUSE: DMTCP was built with Intel icx compiler, which links
# libintlc.so.5 (Intel C runtime). When libdmtcp.so is LD_PRELOAD'd,
# its constructor triggers __intel_cpu_features_init_body which calls
# openat() to read /proc/cpuinfo. But DMTCP wraps openat() via
# dmtcp_openat, creating an infinite recursion loop:
#
#   libdmtcp.so constructor
#     → Intel runtime init (__intel_cpu_features_init_body)
#       → openat("/proc/cpuinfo")
#         → dmtcp_openat wrapper (in libdmtcp.so)
#           → needs Intel runtime (not yet initialized)
#             → __intel_cpu_features_init_body (again)
#               → infinite loop
#
# FIX: Rebuild DMTCP with GCC to avoid Intel runtime dependency.
# MANA must also be rebuilt since it links against DMTCP.
# ============================================================================

set -euo pipefail

INSTALL_PREFIX="${HOME}/.local"
SRC_DIR="${INSTALL_PREFIX}/share/guard-agent/dmtcp-src"
DMTCP_SRC="${SRC_DIR}/dmtcp"
MANA_ROOT="${SRC_DIR}/mana"

echo "============================================================"
echo "  Rebuild DMTCP + MANA with GCC (fix Intel runtime hang)"
echo "============================================================"
echo ""

# ── Step 0: Find GCC ─────────────────────────────────────────────────
GCC_CC=""
GCC_CXX=""

# Try to find gcc/g++ in PATH
if command -v gcc >/dev/null 2>&1; then
    GCC_CC="$(command -v gcc)"
    GCC_CXX="$(command -v g++)"
elif [ -x "/usr/bin/gcc" ]; then
    GCC_CC="/usr/bin/gcc"
    GCC_CXX="/usr/bin/g++"
fi

if [ -z "${GCC_CC}" ]; then
    echo "ERROR: gcc not found in PATH or /usr/bin/"
    echo "Available compilers:"
    command -v cc gcc icx icpx 2>/dev/null || true
    exit 1
fi

echo "Using GCC:"
echo "  CC  = ${GCC_CC}"
echo "  CXX = ${GCC_CXX}"
echo ""

echo "GCC version:"
${GCC_CC} --version | head -1
echo ""

# Verify it's actually GCC (not a symlink to icx)
GCC_ID=$(${GCC_CC} -v 2>&1 | tail -1)
echo "Compiler ID: ${GCC_ID}"
if echo "${GCC_ID}" | grep -qi 'intel\|icx\|icc'; then
    echo "WARNING: 'gcc' appears to be Intel compiler in disguise!"
    echo "Looking for real GCC..."
    
    # On Aurora, real GCC might be in spack
    REAL_GCC=$(find /opt/aurora -name 'gcc' -path '*/bin/gcc' 2>/dev/null | head -1)
    if [ -n "${REAL_GCC}" ]; then
        GCC_CC="${REAL_GCC}"
        GCC_CXX="$(dirname ${REAL_GCC})/g++"
        echo "Found real GCC: ${GCC_CC}"
        ${GCC_CC} --version | head -1
    else
        echo "ERROR: Cannot find real GCC"
        exit 1
    fi
fi
echo ""

# ── Step 1: Clean and reconfigure DMTCP ──────────────────────────────
echo "=== Step 1: Clean and reconfigure DMTCP ==="
echo ""

cd "${DMTCP_SRC}"

echo "Cleaning previous build..."
make distclean 2>/dev/null || make clean 2>/dev/null || true

echo "Reconfiguring with GCC..."
CC="${GCC_CC}" CXX="${GCC_CXX}" ./configure --prefix="${INSTALL_PREFIX}"
echo ""

echo "Verifying Makefile uses GCC:"
grep -E '^CC |^CXX ' Makefile 2>/dev/null | head -5 || true
echo ""

# ── Step 2: Build DMTCP ──────────────────────────────────────────────
echo "=== Step 2: Build DMTCP ==="
echo ""

make -j"$(nproc)" 2>&1 | tail -5
echo ""

echo "Verifying libdmtcp.so (build dir) does NOT link Intel runtime:"
if ldd lib/dmtcp/libdmtcp.so 2>/dev/null | grep -qE 'libintlc'; then
    echo "ERROR: libdmtcp.so still links Intel runtime!"
    echo "Full ldd:"
    ldd lib/dmtcp/libdmtcp.so
    exit 1
else
    echo "  OK - no Intel runtime dependencies in build dir"
fi
echo ""

# Use readelf to check DT_NEEDED (more reliable than ldd which follows transitive deps)
echo "DT_NEEDED entries for libdmtcp.so:"
readelf -d lib/dmtcp/libdmtcp.so 2>/dev/null | grep NEEDED || true
echo ""

# ── Step 3: Install DMTCP ────────────────────────────────────────────
echo "=== Step 3: Install DMTCP ==="
echo ""

make install 2>&1 | tail -5
echo ""

echo "Installed dmtcp_launch:"
file "${INSTALL_PREFIX}/bin/dmtcp_launch" 2>/dev/null || true
echo ""

# Verify installed libdmtcp.so
echo "Verifying installed libdmtcp.so:"
if ldd "${INSTALL_PREFIX}/lib/dmtcp/libdmtcp.so" 2>/dev/null | grep -qE 'libintlc'; then
    echo "ERROR: installed libdmtcp.so still links Intel runtime!"
    ldd "${INSTALL_PREFIX}/lib/dmtcp/libdmtcp.so"
    exit 1
else
    echo "  OK - installed libdmtcp.so has no Intel runtime deps"
fi
echo ""

# ── Step 4: Rebuild MANA ─────────────────────────────────────────────
echo "=== Step 4: Rebuild MANA ==="
echo ""

cd "${MANA_ROOT}"

# Write Aurora Makefile_config with all required settings
# MANA is built with MPI wrappers (mpicc/mpicxx/mpifort) which use Intel compilers,
# but that's OK — only DMTCP itself must avoid Intel runtime.
cat > mpi-proxy-split/Makefile_config << 'MKEOF'
# Aurora (ALCF) – Cray MPICH + Intel GPU
# Auto-generated by rebuild_dmtcp_gcc.sh
# MANA uses MPI wrappers (which use Intel compilers) — that's fine.
# Only DMTCP itself must be built with GCC.

CFLAGS = -g -O2 -std=gnu11
CXXFLAGS = -g -O2
FFLAGS = ${CXXFLAGS} -fallow-argument-mismatch

IS_AURORA = 1
MPICC  = mpicc
MPICXX = mpicxx -std=c++14
MPIFORTRAN = mpifort
MPI_LD_FLAG = -L. -lmpi
MPIRUN = mpiexec
MPI_CFLAGS  ?= -g -O2 -std=gnu11 -g3 -fPIC
MPI_CXXFLAGS ?= -g -O2 -g3 -fPIC
MPI_LDFLAGS ?=
MKEOF

echo "Updated Makefile_config:"
cat mpi-proxy-split/Makefile_config
echo ""

# Apply patches for Clang/icpx compatibility (MANA is built with mpicc which uses icx)
echo "Applying MANA patches..."

# Patch 1: mpi_nextfunc.h - &MPI_##func → &PMPI_##func
NEXTFUNC_H="mpi-proxy-split/mpi-wrappers/mpi_nextfunc.h"
if [ -f "${NEXTFUNC_H}" ] && grep -q '&MPI_##func' "${NEXTFUNC_H}"; then
    sed -i 's/\&MPI_##func/\&PMPI_##func/g' "${NEXTFUNC_H}"
    echo "  Patched ${NEXTFUNC_H}: &MPI_##func → &PMPI_##func"
fi

# Patch 2: record-replay.h - same fix
RR_H="mpi-proxy-split/mpi-wrappers/record-replay.h"
if [ -f "${RR_H}" ] && grep -q '&MPI_##func' "${RR_H}"; then
    sed -i 's/\&MPI_##func/\&PMPI_##func/g' "${RR_H}"
    echo "  Patched ${RR_H}: &MPI_##func → &PMPI_##func"
fi

# Patch 5: PMPI_MANA_Internal compat define
MANA_INTERNAL_H="mpi-proxy-split/mpi-wrappers/mpi_nextfunc.h"
if [ -f "${MANA_INTERNAL_H}" ] && ! grep -q 'PMPI_MANA_Internal' "${MANA_INTERNAL_H}"; then
    sed -i '1i #define PMPI_MANA_Internal MPI_MANA_Internal' "${MANA_INTERNAL_H}"
    echo "  Added PMPI_MANA_Internal compat define"
fi

# Patch 6: switch-context.cpp rex.W → .byte 0x48
SWITCH_CTX="mpi-proxy-split/lower-half/switch-context.cpp"
if [ -f "${SWITCH_CTX}" ] && grep -q 'rex\.W' "${SWITCH_CTX}"; then
    sed -i 's/rex\.W/.byte 0x48/g' "${SWITCH_CTX}"
    echo "  Patched ${SWITCH_CTX}: rex.W → .byte 0x48"
fi

# Patch 7: copy-stack.c void* → char* cast
COPY_STACK="mpi-proxy-split/lower-half/copy-stack.c"
if [ -f "${COPY_STACK}" ] && grep -q 'void \*sp = ' "${COPY_STACK}"; then
    sed -i 's/void \*sp = /char *sp = (char*)/g' "${COPY_STACK}"
    echo "  Patched ${COPY_STACK}: void* → char*"
fi

echo ""

# Clean and rebuild MANA
echo "Cleaning MANA..."
make clean 2>&1 | tail -3 || true
echo ""

echo "Building MANA..."
if ! make -j"$(nproc)" 2>&1; then
    echo ""
    echo "WARNING: MANA build failed. Checking if libmana.so was built..."
    if [ -f "lib/dmtcp/libmana.so" ]; then
        echo "  libmana.so exists — partial build may be usable"
    else
        echo "  libmana.so NOT found — build failed completely"
        echo ""
        echo "  Try building without Fortran support:"
        echo "  cd ${MANA_ROOT} && make clean && make -j\$(nproc) MPIFORTRAN= 2>&1"
    fi
fi
echo ""

echo "Installing MANA..."
make install 2>&1 | tail -5 || true
echo ""

# ── Step 5: Verify ───────────────────────────────────────────────────
echo "=== Step 5: Verification ==="
echo ""

echo "--- Checking installed libdmtcp.so (DT_NEEDED) ---"
readelf -d "${INSTALL_PREFIX}/lib/dmtcp/libdmtcp.so" 2>/dev/null | grep NEEDED || true
echo ""

echo "--- ldd of installed libdmtcp.so ---"
ldd "${INSTALL_PREFIX}/lib/dmtcp/libdmtcp.so" 2>/dev/null || true
echo ""

if [ -f "${MANA_ROOT}/lib/dmtcp/libmana.so" ]; then
    echo "--- MANA libmana.so exists ---"
    ls -la "${MANA_ROOT}/lib/dmtcp/libmana.so"
else
    echo "--- WARNING: libmana.so NOT found ---"
fi
echo ""

if [ -f "${MANA_ROOT}/bin/lower-half" ]; then
    echo "--- lower-half exists ---"
    ls -la "${MANA_ROOT}/bin/lower-half"
    echo "lower-half MPI deps:"
    ldd "${MANA_ROOT}/bin/lower-half" 2>/dev/null | grep -iE 'mpi|cray|fabric' || echo "  (none)"
else
    echo "--- WARNING: lower-half NOT found ---"
fi
echo ""

if [ -f "${MANA_ROOT}/lib/dmtcp/libmpistub.so" ]; then
    echo "--- libmpistub.so exists ---"
    ls -la "${MANA_ROOT}/lib/dmtcp/libmpistub.so"
else
    echo "--- WARNING: libmpistub.so NOT found ---"
fi
echo ""

# ── Step 6: Quick DMTCP test ─────────────────────────────────────────
echo "=== Step 6: Quick DMTCP test ==="
echo ""

export HWLOC_COMPONENTS="-linuxio"

# Test LD_PRELOAD directly (this was the hang test)
cat > /tmp/hello_dmtcp_test.c << 'EOF'
#include <stdio.h>
#include <unistd.h>
int main() {
    printf("Hello from DMTCP test (pid=%d)\n", getpid());
    fflush(stdout);
    return 0;
}
EOF

${GCC_CC} -o /tmp/hello_dmtcp_test /tmp/hello_dmtcp_test.c 2>&1

echo "Test 1: LD_PRELOAD=libdmtcp.so hello (should NOT hang):"
if timeout 5 env LD_PRELOAD="${INSTALL_PREFIX}/lib/dmtcp/libdmtcp.so" /tmp/hello_dmtcp_test 2>&1; then
    echo "  PASS"
else
    RC=$?
    echo "  Exit code: ${RC}"
    if [ "${RC}" -eq 124 ]; then
        echo "  FAIL: Process timed out (still hanging!)"
    fi
fi
echo ""

echo "Test 2: dmtcp_launch with new coordinator:"
# Start a fresh coordinator
"${INSTALL_PREFIX}/bin/dmtcp_coordinator" --daemon --coord-port 0 \
    --port-file /tmp/dmtcp_test_port.txt -q 2>&1 || true
sleep 1
if [ -f /tmp/dmtcp_test_port.txt ]; then
    TEST_PORT=$(cat /tmp/dmtcp_test_port.txt)
    echo "  Coordinator started on port ${TEST_PORT}"
    if timeout 10 "${INSTALL_PREFIX}/bin/dmtcp_launch" \
        --coord-port "${TEST_PORT}" -j /tmp/hello_dmtcp_test 2>&1; then
        echo "  PASS"
    else
        RC=$?
        echo "  Exit code: ${RC}"
        if [ "${RC}" -eq 124 ]; then
            echo "  FAIL: Process timed out (still hanging!)"
        fi
    fi
    # Kill coordinator
    "${INSTALL_PREFIX}/bin/dmtcp_command" --port "${TEST_PORT}" -q 2>/dev/null || true
    rm -f /tmp/dmtcp_test_port.txt
else
    echo "  Could not start coordinator (port file not created)"
fi
echo ""

# Cleanup
rm -f /tmp/hello_dmtcp_test /tmp/hello_dmtcp_test.c

echo "============================================================"
echo "  Rebuild complete!"
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. If MANA build failed, try: cd ${MANA_ROOT} && make clean && make -j\$(nproc) MPIFORTRAN= 2>&1"
echo "  2. Test MANA: ${MANA_ROOT}/bin/mana_start_coordinator && mpiexec -n 1 ${MANA_ROOT}/bin/mana_launch \$(hostname) \${MANA_ROOT}/bin/send_recv_loop.mana.exe"
echo "  3. Test art_simple: bash tests/examples/dmtcp/art_simple/test_mana_aurora.sh"
