# Validation framework for code generated by agents/veloc.
#
# Public API
# ----------
# runner            – build, run, and failure-injection orchestration
# comparator        – pluggable output comparison strategies
# metrics_collector – benchmarking and metrics collection
# reporter          – graphical plots and summary report generation
# validate          – main entry point (python -m validation.veloc.validate)

from .runner import (
    RunResult,
    ValidationError,
    configure_and_build,
    run_once,
    run_baseline,
    run_with_failure_injection,
    extract_checkpoint_dirs_from_veloc_cfg,
    clear_checkpoint_dirs,
)
from .comparator import (
    CompareResult,
    BaseComparator,
    HashComparator,
    SSIMComparator,
    NumericToleranceComparator,
    TextDiffComparator,
    CustomPluginComparator,
    make_comparator,
)
from .metrics_collector import (
    BenchmarkScenario,
    RunMetrics,
    BenchmarkResults,
    load_benchmark_config,
    default_scenario,
    run_benchmark_sweep,
)
from .reporter import generate_report

__all__ = [
    # runner
    "RunResult",
    "ValidationError",
    "configure_and_build",
    "run_once",
    "run_baseline",
    "run_with_failure_injection",
    "extract_checkpoint_dirs_from_veloc_cfg",
    "clear_checkpoint_dirs",
    # comparator
    "CompareResult",
    "BaseComparator",
    "HashComparator",
    "SSIMComparator",
    "NumericToleranceComparator",
    "TextDiffComparator",
    "CustomPluginComparator",
    "make_comparator",
    # metrics_collector
    "BenchmarkScenario",
    "RunMetrics",
    "BenchmarkResults",
    "load_benchmark_config",
    "default_scenario",
    "run_benchmark_sweep",
    # reporter
    "generate_report",
]
