# Validation framework for code generated by agents/veloc.
#
# Public API
# ----------
# runner            – build, run, and failure-injection orchestration
# comparator        – pluggable output comparison strategies
# metrics_collector – benchmarking and metrics collection
# reporter          – graphical plots and summary report generation
# validate          – main entry point (python -m validation.veloc.validate)
#
# F-10 — Framework version invariant
# ----------------------------------
# Bump FRAMEWORK_VERSION on EVERY commit that touches the measurement
# stack: validate.py, runner.py, metrics_collector.py, reporter.py,
# reference_validator.py.  Every result artifact records this version so
# the trust gate can refuse to accept a unit whose recorded version
# doesn't match the current code's — forcing demote-to-UNTRUSTED + re-
# measure on framework change (Operating Principle 9).
#
# Format: "YYYY-MM-DD" (date of the most recent measurement-stack edit).
# Bumped in lockstep with _decisions.log "framework_change" entries.
FRAMEWORK_VERSION = "2026-05-15"

from .runner import (
    RunResult,
    ValidationError,
    configure_and_build,
    run_once,
    run_baseline,
    run_with_failure_injection,
    extract_checkpoint_dirs_from_veloc_cfg,
    clear_checkpoint_dirs,
)
from .comparator import (
    CompareResult,
    BaseComparator,
    HashComparator,
    SSIMComparator,
    NumericToleranceComparator,
    TextDiffComparator,
    CustomPluginComparator,
    make_comparator,
)
from .metrics_collector import (
    BenchmarkScenario,
    RunMetrics,
    BenchmarkResults,
    load_benchmark_config,
    default_scenario,
    run_benchmark_sweep,
)
from .reporter import generate_report

__all__ = [
    # runner
    "RunResult",
    "ValidationError",
    "configure_and_build",
    "run_once",
    "run_baseline",
    "run_with_failure_injection",
    "extract_checkpoint_dirs_from_veloc_cfg",
    "clear_checkpoint_dirs",
    # comparator
    "CompareResult",
    "BaseComparator",
    "HashComparator",
    "SSIMComparator",
    "NumericToleranceComparator",
    "TextDiffComparator",
    "CustomPluginComparator",
    "make_comparator",
    # metrics_collector
    "BenchmarkScenario",
    "RunMetrics",
    "BenchmarkResults",
    "load_benchmark_config",
    "default_scenario",
    "run_benchmark_sweep",
    # reporter
    "generate_report",
]
