"""
exampm_comparator.py – Custom comparator plugin for ExaMPM validation.

Plugin contract (see validation/veloc/comparator.py):
    def compare(baseline_path: str, resilient_path: str, **kwargs) -> dict

This plugin performs **two** levels of comparison:

1. **Stdout time-progress comparison** – parses the per-timestep progress
   output printed to stdout by ExaMPM and compares the simulation time
   values with a tight relative tolerance.

2. **HDF5 particle-output comparison** – compares the ``particles_*.h5``
   files generated by Cabana's HDF5ParticleOutput in the same output
   directory.  Each HDF5 file contains:
     - ``Time`` attribute (scalar float64)
     - ``J`` dataset (N floats)
     - ``position`` dataset (N×3 floats)
     - ``velocity`` dataset (N×3 floats)

   Files are matched by name (e.g. ``particles_5.h5``).  Only the
   **last** (highest-numbered) common file is compared by default, since
   earlier files may not exist in the resilient output after a restart.
   Set ``compare_all_h5=True`` via kwargs to compare every common file.

ExaMPM stdout format
--------------------
The solver prints a progress line at every ``write_freq`` steps (only on
rank 0):

    Time 0.000000 / 1.000000
    Time 0.010000 / 1.000000
    Time 0.020000 / 1.000000
    ...
    Time 0.990000 / 1.000000

Each line contains the current simulation time and the final time.

Physics columns (compared with relative tolerance):
    current_time, t_final

Non-deterministic content (ignored):
    Cabana/HDF5/Silo output messages, Kokkos initialization messages

Correctness criterion
---------------------
All per-output-step time values must match within ``rtol`` (default 1e-6)
between the baseline and resilient runs.  When HDF5 files are present,
the particle data (position, velocity, J) must also match within the
same tolerance.

The resilient run may restart from a VeloC checkpoint, so early timestep
rows may be absent from the resilient output.  Only **common** output
indices are compared.

Score: fraction of common output steps where the time values match within
tolerance (1.0 = perfect).  When HDF5 comparison is performed, the score
is the minimum of the stdout score and the HDF5 score.

Usage
-----
This file is loaded by CustomPluginComparator via:
    --comparison-method custom
    --custom-comparator validation/veloc/exampm_comparator.py
    --output-file-name stdout.txt
"""

from __future__ import annotations

import glob
import math
import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Column definitions
# ---------------------------------------------------------------------------

# Default relative tolerance for floating-point comparison.
DEFAULT_RTOL = 1e-6

# Default absolute tolerance for HDF5 dataset comparison.
DEFAULT_ATOL = 1e-6

# Regex: ExaMPM progress line.
# Matches: "Time 0.010000 / 1.000000"
_TIME_LINE_RE = re.compile(
    r"^\s*Time\s+([0-9eE.+-]+)\s*/\s*([0-9eE.+-]+)\s*$"
)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def _parse_time_progress(
    text: str,
) -> list[dict[str, float]]:
    """Parse the time progress lines from ExaMPM stdout.

    Returns a list of dicts, each with keys ``current_time`` and ``t_final``,
    in the order they appear in the output.  Duplicate entries (from restarts)
    are kept; the comparison logic handles deduplication via index matching.
    """
    rows: list[dict[str, float]] = []

    for line in text.splitlines():
        m = _TIME_LINE_RE.match(line)
        if not m:
            continue

        try:
            current_time = float(m.group(1))
            t_final = float(m.group(2))
            rows.append({
                "current_time": current_time,
                "t_final": t_final,
            })
        except (ValueError, IndexError):
            continue

    return rows


def _deduplicate_by_time(
    rows: list[dict[str, float]],
) -> dict[str, dict[str, float]]:
    """Convert a list of time-progress rows into a dict keyed by a
    canonical time string (to avoid floating-point key issues).

    If the same time appears multiple times (e.g. after a restart), the
    **last** occurrence wins (the restart re-emits earlier timesteps and
    then continues).
    """
    result: dict[str, dict[str, float]] = {}
    for row in rows:
        # Use a canonical string key with enough precision.
        key = f"{row['current_time']:.10f}"
        result[key] = row
    return result


# ---------------------------------------------------------------------------
# Comparison logic
# ---------------------------------------------------------------------------

def _values_close(a: float, b: float, rtol: float) -> bool:
    """Return True if |a - b| / max(|a|, |b|, 1e-300) <= rtol."""
    denom = max(abs(a), abs(b), 1e-300)
    return abs(a - b) / denom <= rtol


def _compare_time_progress(
    baseline: dict[str, dict[str, float]],
    resilient: dict[str, dict[str, float]],
    rtol: float = DEFAULT_RTOL,
) -> tuple[bool, float, str, dict[str, Any]]:
    """Compare two time-progress dicts.

    Returns ``(passed, score, message, details)``.
    """
    if not baseline:
        return (
            False,
            0.0,
            "No time progress lines found in baseline stdout.txt",
            {"baseline_steps": 0, "resilient_steps": len(resilient)},
        )
    if not resilient:
        return (
            False,
            0.0,
            "No time progress lines found in resilient stdout.txt",
            {"baseline_steps": len(baseline), "resilient_steps": 0},
        )

    baseline_keys = sorted(baseline.keys())
    resilient_keys = sorted(resilient.keys())

    # The resilient run may have fewer timesteps if it restarted from a
    # checkpoint.  Compare only the time keys present in BOTH outputs.
    common_keys = sorted(set(baseline_keys) & set(resilient_keys))

    if not common_keys:
        return (
            False,
            0.0,
            (
                f"No common time steps between baseline ({baseline_keys[:5]}…) "
                f"and resilient ({resilient_keys[:5]}…)"
            ),
            {
                "baseline_keys": baseline_keys,
                "resilient_keys": resilient_keys,
                "common_keys": [],
            },
        )

    mismatches: list[dict[str, Any]] = []
    for key in common_keys:
        b_row = baseline[key]
        r_row = resilient[key]
        step_mismatches: dict[str, dict[str, Any]] = {}

        for col in ("current_time", "t_final"):
            b_val = b_row.get(col)
            r_val = r_row.get(col)
            if b_val is None or r_val is None:
                step_mismatches[col] = {
                    "baseline": b_val,
                    "resilient": r_val,
                    "reason": "missing value",
                }
            elif not _values_close(b_val, r_val, rtol):
                rel_err = abs(b_val - r_val) / max(abs(b_val), abs(r_val), 1e-300)
                step_mismatches[col] = {
                    "baseline": b_val,
                    "resilient": r_val,
                    "rel_err": rel_err,
                }
        if step_mismatches:
            mismatches.append({"time_key": key, "columns": step_mismatches})

    total_steps = len(common_keys)
    matching_steps = total_steps - len(mismatches)
    score = matching_steps / total_steps if total_steps > 0 else 0.0
    passed = len(mismatches) == 0

    if passed:
        message = (
            f"All {total_steps} common time step(s) match within rtol={rtol:.1e} "
            f"(baseline={len(baseline_keys)} steps, "
            f"resilient={len(resilient_keys)} steps)"
        )
    else:
        message = (
            f"{len(mismatches)}/{total_steps} time step(s) have mismatches "
            f"(rtol={rtol:.1e}; "
            f"baseline={len(baseline_keys)} steps, "
            f"resilient={len(resilient_keys)} steps)"
        )

    details: dict[str, Any] = {
        "rtol": rtol,
        "baseline_keys": baseline_keys,
        "resilient_keys": resilient_keys,
        "common_keys": common_keys,
        "total_common_steps": total_steps,
        "matching_steps": matching_steps,
        "mismatched_steps": len(mismatches),
        # Cap mismatch details at 10 entries to keep the report readable.
        "mismatches": mismatches[:10],
    }

    return passed, score, message, details


# ---------------------------------------------------------------------------
# HDF5 particle output comparison
# ---------------------------------------------------------------------------

def _find_particle_h5_files(directory: Path) -> dict[str, Path]:
    """Find all ``particles_*.h5`` files in *directory* and its ``attempt_*``
    subdirectories (used by the resilient runner's failure-injection loop).

    Returns a dict mapping the filename stem (e.g. ``"particles_5"``) to the
    full path, sorted by the numeric index.  If the same stem appears in
    multiple attempt directories, the one from the highest-numbered attempt
    wins (that is the successful run).
    """
    result: dict[str, Path] = {}

    # First, check the directory itself (baseline and resilient_clean runs).
    for p in sorted(directory.glob("particles_*.h5")):
        result[p.stem] = p

    # Then, check attempt_* subdirectories (resilient failure-injection runs).
    # Later attempts override earlier ones, so the successful attempt's files
    # take precedence.
    for attempt_dir in sorted(directory.glob("attempt_*")):
        if attempt_dir.is_dir():
            for p in sorted(attempt_dir.glob("particles_*.h5")):
                result[p.stem] = p

    return result


def _compare_h5_datasets(
    baseline_h5: Path,
    resilient_h5: Path,
    rtol: float,
    atol: float,
) -> tuple[bool, str, dict[str, Any]]:
    """Compare two ExaMPM HDF5 particle files element-wise.

    Compares the ``Time`` attribute and the ``J``, ``position``, ``velocity``
    datasets using ``numpy.allclose(atol, rtol)``.

    Returns ``(passed, message, details)``.
    """
    try:
        import h5py
        import numpy as np
    except ImportError as exc:
        return (
            False,
            f"HDF5 comparison failed: {exc}. Install with: pip install h5py numpy",
            {"error": str(exc)},
        )

    try:
        fb = h5py.File(baseline_h5, "r")
        fr = h5py.File(resilient_h5, "r")
    except OSError as exc:
        return (
            False,
            f"Cannot open HDF5 files: {exc}",
            {"error": str(exc)},
        )

    try:
        details: dict[str, Any] = {"file": str(baseline_h5.name)}
        all_ok = True
        dataset_results: dict[str, dict[str, Any]] = {}

        # Compare Time attribute
        if "Time" in fb.attrs and "Time" in fr.attrs:
            t_base = float(fb.attrs["Time"])
            t_res = float(fr.attrs["Time"])
            time_ok = _values_close(t_base, t_res, rtol)
            dataset_results["Time"] = {
                "baseline": t_base,
                "resilient": t_res,
                "match": time_ok,
            }
            if not time_ok:
                all_ok = False

        # Compare datasets: J, position, velocity
        for ds_name in ("J", "position", "velocity"):
            if ds_name not in fb or ds_name not in fr:
                dataset_results[ds_name] = {
                    "skipped": True,
                    "reason": f"Dataset missing in {'baseline' if ds_name not in fb else 'resilient'}",
                }
                continue

            arr_b = fb[ds_name][...]
            arr_r = fr[ds_name][...]

            if arr_b.shape != arr_r.shape:
                dataset_results[ds_name] = {
                    "match": False,
                    "reason": f"Shape mismatch: {arr_b.shape} vs {arr_r.shape}",
                }
                all_ok = False
                continue

            abs_diff = np.abs(arr_b.astype(float) - arr_r.astype(float))
            max_abs = float(abs_diff.max())
            denom = np.maximum(np.abs(arr_b.astype(float)), 1e-300)
            max_rel = float((abs_diff / denom).max())
            ds_ok = bool(np.allclose(arr_b, arr_r, atol=atol, rtol=rtol))

            dataset_results[ds_name] = {
                "match": ds_ok,
                "max_abs_diff": max_abs,
                "max_rel_diff": max_rel,
                "shape": list(arr_b.shape),
            }
            if not ds_ok:
                all_ok = False

        details["datasets"] = dataset_results

        if all_ok:
            msg = f"HDF5 {baseline_h5.name}: all datasets match (rtol={rtol:.1e}, atol={atol:.1e})"
        else:
            failed = [k for k, v in dataset_results.items() if not v.get("match", True)]
            msg = f"HDF5 {baseline_h5.name}: mismatch in {', '.join(failed)}"

        return all_ok, msg, details

    finally:
        fb.close()
        fr.close()


def _compare_particle_h5(
    baseline_dir: Path,
    resilient_dir: Path,
    rtol: float,
    atol: float,
    compare_all: bool = False,
) -> tuple[bool, float, str, dict[str, Any]]:
    """Compare HDF5 particle output files between baseline and resilient runs.

    Parameters
    ----------
    baseline_dir:
        Directory containing baseline ``particles_*.h5`` files.
    resilient_dir:
        Directory containing resilient ``particles_*.h5`` files.
    rtol:
        Relative tolerance for element-wise comparison.
    atol:
        Absolute tolerance for element-wise comparison.
    compare_all:
        If True, compare all common files.  If False (default), compare
        only the last (highest-numbered) common file.

    Returns ``(passed, score, message, details)``.
    """
    baseline_files = _find_particle_h5_files(baseline_dir)
    resilient_files = _find_particle_h5_files(resilient_dir)

    if not baseline_files:
        return (
            False,
            0.0,
            "FAIL: No particles_*.h5 files found in baseline output. "
            "HDF5 particle output is required for validation.",
            {"reason": "no baseline HDF5 files", "baseline_dir": str(baseline_dir)},
        )

    if not resilient_files:
        return (
            False,
            0.0,
            "FAIL: No particles_*.h5 files found in resilient output. "
            "HDF5 particle output is required for validation.",
            {"reason": "no resilient HDF5 files", "resilient_dir": str(resilient_dir)},
        )

    common_stems = sorted(set(baseline_files.keys()) & set(resilient_files.keys()))
    if not common_stems:
        return (
            False,
            0.0,
            (
                f"FAIL: No common particles_*.h5 files between baseline "
                f"({sorted(baseline_files.keys())}) and resilient "
                f"({sorted(resilient_files.keys())})"
            ),
            {
                "baseline_files": sorted(baseline_files.keys()),
                "resilient_files": sorted(resilient_files.keys()),
            },
        )

    # Select which files to compare.
    if compare_all:
        stems_to_compare = common_stems
    else:
        # Compare only the last common file (highest index).
        stems_to_compare = [common_stems[-1]]

    all_passed = True
    file_results: list[dict[str, Any]] = []
    messages: list[str] = []

    for stem in stems_to_compare:
        ok, msg, det = _compare_h5_datasets(
            baseline_files[stem], resilient_files[stem], rtol=rtol, atol=atol,
        )
        file_results.append({"stem": stem, "passed": ok, "message": msg, **det})
        messages.append(msg)
        if not ok:
            all_passed = False

    total = len(stems_to_compare)
    passed_count = sum(1 for r in file_results if r["passed"])
    score = passed_count / total if total > 0 else 1.0

    summary = "; ".join(messages)
    details: dict[str, Any] = {
        "baseline_h5_count": len(baseline_files),
        "resilient_h5_count": len(resilient_files),
        "common_stems": common_stems,
        "compared_stems": stems_to_compare,
        "file_results": file_results,
    }

    return all_passed, score, summary, details


# ---------------------------------------------------------------------------
# Plugin entry point
# ---------------------------------------------------------------------------

def compare(baseline_path: str, resilient_path: str, **kwargs: Any) -> dict:
    """Parse ExaMPM time progress lines and compare simulation times.

    Also compares HDF5 particle output files (``particles_*.h5``) if they
    exist in the same directory as the stdout files.

    Parameters
    ----------
    baseline_path:
        Path to the baseline ``stdout.txt`` file.
    resilient_path:
        Path to the resilient ``stdout.txt`` file.
    rtol:
        Relative tolerance for floating-point comparison (default: 1e-6).
        Can be passed as a keyword argument.
    atol:
        Absolute tolerance for HDF5 dataset comparison (default: 1e-6).
    compare_all_h5:
        If True, compare all common HDF5 files.  If False (default),
        compare only the last (highest-numbered) common file.
    **kwargs:
        Additional keyword arguments are ignored.

    Returns
    -------
    dict with keys:
        passed  : bool   – True if both stdout and HDF5 comparisons pass
        score   : float  – minimum of stdout and HDF5 scores
        message : str    – human-readable summary
        details : dict   – per-step mismatch information and HDF5 results
    """
    rtol = float(kwargs.get("rtol", DEFAULT_RTOL))
    atol = float(kwargs.get("atol", DEFAULT_ATOL))
    compare_all_h5 = bool(kwargs.get("compare_all_h5", False))

    b_path = Path(baseline_path)
    r_path = Path(resilient_path)

    # Read files.
    try:
        baseline_text = b_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return {
            "passed": False,
            "score": 0.0,
            "message": f"Cannot read baseline file {b_path}: {exc}",
            "details": {},
        }

    try:
        resilient_text = r_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return {
            "passed": False,
            "score": 0.0,
            "message": f"Cannot read resilient file {r_path}: {exc}",
            "details": {},
        }

    # Parse time progress lines.
    baseline_rows = _parse_time_progress(baseline_text)
    resilient_rows = _parse_time_progress(resilient_text)

    # Deduplicate by canonical time key (handles restarts).
    baseline_dict = _deduplicate_by_time(baseline_rows)
    resilient_dict = _deduplicate_by_time(resilient_rows)

    stdout_passed, stdout_score, stdout_message, stdout_details = _compare_time_progress(
        baseline_dict, resilient_dict, rtol=rtol
    )

    # --- HDF5 particle output comparison ---
    # The HDF5 files are in the same directory as the stdout.txt files.
    baseline_dir = b_path.parent
    resilient_dir = r_path.parent

    h5_passed, h5_score, h5_message, h5_details = _compare_particle_h5(
        baseline_dir, resilient_dir, rtol=rtol, atol=atol,
        compare_all=compare_all_h5,
    )

    # --- Combine results ---
    overall_passed = stdout_passed and h5_passed
    overall_score = min(stdout_score, h5_score) if stdout_score is not None else h5_score

    # Build combined message.
    combined_message = f"[stdout] {stdout_message} | [HDF5] {h5_message}"

    combined_details = {
        "stdout": stdout_details,
        "hdf5": h5_details,
    }

    return {
        "passed": overall_passed,
        "score": overall_score,
        "message": combined_message,
        "details": combined_details,
    }


# ---------------------------------------------------------------------------
# CLI self-test (run directly: python exampm_comparator.py <f1> <f2>)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json
    import sys

    if len(sys.argv) < 3:
        print(
            f"Usage: {sys.argv[0]} <baseline_stdout.txt> <resilient_stdout.txt> "
            f"[rtol] [atol] [--all-h5]"
        )
        sys.exit(1)

    # Filter out flags before parsing positional args.
    _positional = [a for a in sys.argv[3:] if not a.startswith("--")]
    _rtol = float(_positional[0]) if len(_positional) > 0 else DEFAULT_RTOL
    _atol = float(_positional[1]) if len(_positional) > 1 else DEFAULT_ATOL
    _all_h5 = "--all-h5" in sys.argv
    result = compare(
        sys.argv[1], sys.argv[2],
        rtol=_rtol, atol=_atol, compare_all_h5=_all_h5,
    )
    print(json.dumps(result, indent=2))
    sys.exit(0 if result["passed"] else 1)
