#!/usr/bin/env bash
# Run the full VeloC validation pipeline for ExaMiniMD vs resilient_ExaMiniMD.
#
# Baseline (original):  build/ecp/ExaMiniMD  (BUILD_DIR sandbox copy)
# Resilient:            build/ecp_output/resilient_ExaMiniMD
#
# Usage (from repo root):
#   ./validation/veloc/run_examinimd_validation.sh [--skip-benchmarks] [--skip-report]
#
# Optional environment variables:
#   ORIGINAL_DIR   – path to the original ExaMiniMD codebase
#                    (default: build/ecp/ExaMiniMD — BUILD_DIR sandbox copy)
#   RESILIENT_DIR  – path to the resilient codebase generated by agents/veloc
#                    (default: build/ecp_output/resilient_ExaMiniMD)
#   INPUT_FILE     – path to the LAMMPS input file used for correctness validation
#                    (default: build/ecp/ExaMiniMD/input/in.lj)
#   INPUT_DIR      – directory containing the workload-variant input files
#                    (default: build/ecp/ExaMiniMD/input)
#                    (exported so benchmark JSON config can expand ${INPUT_DIR:-...})
#   NUM_PROCS      – number of MPI ranks             (default: 4)
#   OUTPUT_DIR     – validation output directory     (default: build/validation_output/examinimd)
#   NUM_RUNS       – override benchmark repetitions for ALL scenarios (unset by default;
#                    when unset, each scenario uses its own num_runs from the JSON config;
#                    set to 1 for a quick smoke-test: NUM_RUNS=1 ./run_examinimd_validation.sh)
#
# Benchmark scenarios are defined in:
#   validation/veloc/benchmark_configs/examinimd.json
# Each scenario specifies its own num_runs, num_procs, app_args, and failure injection settings.
# NUM_RUNS (if set) takes priority over per-scenario num_runs in the JSON.
#
# Comparison method:
#   Custom plugin: validation/veloc/examinimd_comparator.py
#   Parses the per-timestep thermodynamic output table from stdout.txt and compares
#   the three physics columns (Temperature, PotE, ETot) with relative tolerance 1e-6.
#   Timing columns (Time, Atomsteps/s) and the PERFORMANCE summary line are ignored.
#
# Input file variants:
#   ExaMiniMD does not support CLI overrides for the number of timesteps.
#   This script generates three input file variants in INPUT_DIR before running:
#     in.lj.short   – run 50   (50 timesteps)
#     in.lj.medium  – run 100  (100 timesteps, same as default in.lj)
#     in.lj.long    – run 200  (200 timesteps)
#   These files are identical to in.lj except for the final "run N" line.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Activate virtualenv if available (created by ./setup.sh).
if [[ -d "build/venv" ]]; then
  # shellcheck disable=SC1091
  source "build/venv/bin/activate"

  # Ensure validation Python dependencies are installed (matplotlib, numpy, etc.)
  REQS="${REPO_ROOT}/validation/requirements.txt"
  if [[ -f "${REQS}" ]]; then
    pip install -q -r "${REQS}"
  fi
fi

export PYTHONPATH="${REPO_ROOT}:${PYTHONPATH:-}"

# ---------------------------------------------------------------------------
# Configurable paths and parameters
# ---------------------------------------------------------------------------
ORIGINAL_DIR="${ORIGINAL_DIR:-${REPO_ROOT}/build/ecp/ExaMiniMD}"
RESILIENT_DIR="${RESILIENT_DIR:-${REPO_ROOT}/build/ecp_output/resilient_ExaMiniMD}"
# Use the BUILD_DIR sandbox copy so we never modify the source tree.
# setup.sh copies tests/ecp/vanillas/* → build/ecp/*.
INPUT_FILE="${INPUT_FILE:-${REPO_ROOT}/build/ecp/ExaMiniMD/input/in.lj}"
# Export INPUT_DIR so the benchmark JSON config can expand ${INPUT_DIR:-...} via os.environ.
# Generated workload variants (in.lj.short/medium/long) are written here.
export INPUT_DIR="${INPUT_DIR:-${REPO_ROOT}/build/ecp/ExaMiniMD/input}"
NUM_PROCS="${NUM_PROCS:-4}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/build/validation_output/examinimd}"

BENCHMARK_CONFIG="${REPO_ROOT}/validation/veloc/benchmark_configs/examinimd.json"
CUSTOM_COMPARATOR="${REPO_ROOT}/validation/veloc/examinimd_comparator.py"

# ExaMiniMD CLI arguments for correctness validation (medium workload):
#   -il <input_file>       LAMMPS-format input file
#   --comm-type MPI        Use MPI communication layer
#   --kokkos-threads=1     1 Kokkos thread per MPI rank (avoids oversubscription)
COMMON_ARGS="-il ${INPUT_FILE} --comm-type MPI --kokkos-threads=1"

STATE_FILE="${OUTPUT_DIR}/pipeline_state.json"

# ---------------------------------------------------------------------------
# Generate workload-variant input files (short / medium / long)
# ---------------------------------------------------------------------------
# ExaMiniMD reads the number of timesteps from the "run N" line in the input
# file.  There is no CLI flag to override it.  We generate three variants of
# the base input file that differ only in the final "run N" line.
#
# The base input file is INPUT_FILE (default: input/in.lj).
# Variants are written to INPUT_DIR as in.lj.short, in.lj.medium, in.lj.long.
# ---------------------------------------------------------------------------

_generate_input_variants() {
  local base_input="${INPUT_FILE}"
  local out_dir="${INPUT_DIR}"

  if [[ ! -f "${base_input}" ]]; then
    echo "[run] WARNING: base input file not found: ${base_input}"
    echo "[run]          Skipping input variant generation."
    echo "[run]          Benchmark scenarios that reference in.lj.{short,medium,long}"
    echo "[run]          will fail unless those files already exist."
    return
  fi

  echo "[run] Generating workload-variant input files in: ${out_dir}"

  # Strip the existing "run N" line and append the desired count.
  # We use grep -v to remove any existing "run " line, then append the new one.
  local base_no_run
  base_no_run="$(grep -v '^\s*run\s' "${base_input}")"

  for variant in short medium long; do
    local nsteps
    case "${variant}" in
      short)  nsteps=50  ;;
      medium) nsteps=100 ;;
      long)   nsteps=200 ;;
    esac
    local out_file="${out_dir}/in.lj.${variant}"
    printf '%s\nrun\t\t%d\n' "${base_no_run}" "${nsteps}" > "${out_file}"
    echo "[run]   ${out_file}  (run ${nsteps})"
  done
}

_generate_input_variants

# ---------------------------------------------------------------------------
# Detect incomplete previous run and ask user what to do
# ---------------------------------------------------------------------------
RESUME_FLAG=""

if [[ -f "${STATE_FILE}" ]]; then
  # Check if the run is already finished (has "finished": true in the JSON).
  if python3 -c "
import json, sys
state = json.load(open('${STATE_FILE}'))
sys.exit(0 if state.get('finished') else 1)
" 2>/dev/null; then
    echo ""
    echo "============================================================"
    echo "  A previous validation run in:"
    echo "    ${OUTPUT_DIR}"
    echo "  completed successfully."
    echo "============================================================"
    echo ""
    echo "Options:"
    echo "  [1] Re-run graphical report only  (skip correctness + benchmarks)"
    echo "  [2] Start a fresh run             (deletes previous output)"
    echo "  [3] Exit (keep previous results)"
    echo ""
    read -rp "Your choice [1/2/3]: " CHOICE
    case "${CHOICE}" in
      1)
        echo "[run] Re-running graphical report stage only..."
        RESUME_FLAG="--resume --skip-correctness --skip-benchmarks"
        # Clear the 'report' stage from state so validate.py will re-run it.
        python3 -c "
import json
p = '${STATE_FILE}'
state = json.load(open(p))
state['completed_stages'] = [s for s in state.get('completed_stages', []) if s != 'report']
state['finished'] = False
json.dump(state, open(p, 'w'), indent=2)
"
        ;;
      2)
        echo "[run] Removing previous output directory: ${OUTPUT_DIR}"
        rm -rf "${OUTPUT_DIR}"
        ;;
      *)
        echo "[run] Exiting. Previous results are preserved in ${OUTPUT_DIR}"
        exit 0
        ;;
    esac
  else
    # Incomplete previous run found.
    COMPLETED=$(python3 -c "
import json, sys
try:
    state = json.load(open('${STATE_FILE}'))
    stages = state.get('completed_stages', [])
    print(', '.join(stages) if stages else '(none)')
except Exception:
    print('(unknown)')
" 2>/dev/null || echo "(unknown)")

    LAST_UPDATED=$(python3 -c "
import json, sys
try:
    state = json.load(open('${STATE_FILE}'))
    print(state.get('last_updated') or state.get('started_at') or '(unknown)')
except Exception:
    print('(unknown)')
" 2>/dev/null || echo "(unknown)")

    echo ""
    echo "============================================================"
    echo "  An INCOMPLETE previous validation run was found in:"
    echo "    ${OUTPUT_DIR}"
    echo "  Last updated : ${LAST_UPDATED}"
    echo "  Completed    : ${COMPLETED}"
    echo "============================================================"
    echo ""
    echo "Options:"
    echo "  [1] Resume from last completed stage"
    echo "  [2] Start a completely fresh run  (deletes previous output)"
    echo "  [3] Exit (do nothing)"
    echo ""
    read -rp "Your choice [1/2/3]: " CHOICE
    case "${CHOICE}" in
      1)
        echo "[run] Resuming previous run..."
        RESUME_FLAG="--resume"
        ;;
      2)
        echo "[run] Removing previous output directory: ${OUTPUT_DIR}"
        rm -rf "${OUTPUT_DIR}"
        ;;
      3)
        echo "[run] Exiting. Previous run is preserved in ${OUTPUT_DIR}"
        exit 0
        ;;
      *)
        echo "[run] Invalid choice. Exiting."
        exit 1
        ;;
    esac
  fi
fi

# ---------------------------------------------------------------------------
# Build optional --benchmark-num-runs flag (only when NUM_RUNS is set).
# When NUM_RUNS is set it overrides per-scenario num_runs in the JSON config.
# When NUM_RUNS is unset, per-scenario num_runs from the JSON is used.
# ---------------------------------------------------------------------------
NUM_RUNS_FLAG=""
if [[ -n "${NUM_RUNS:-}" ]]; then
  NUM_RUNS_FLAG="--benchmark-num-runs ${NUM_RUNS}"
fi

# ---------------------------------------------------------------------------
# Run the validation framework
# ---------------------------------------------------------------------------
echo ""
echo "[run] Configuration:"
echo "  ORIGINAL_DIR     : ${ORIGINAL_DIR}"
echo "  RESILIENT_DIR    : ${RESILIENT_DIR}"
echo "  INPUT_FILE       : ${INPUT_FILE}"
echo "  INPUT_DIR        : ${INPUT_DIR}"
echo "  NUM_PROCS        : ${NUM_PROCS}"
echo "  BENCHMARK_CONFIG : ${BENCHMARK_CONFIG}"
echo "  CUSTOM_COMPARATOR: ${CUSTOM_COMPARATOR}"
if [[ -n "${NUM_RUNS:-}" ]]; then
  echo "  NUM_RUNS         : ${NUM_RUNS}  (overrides per-scenario num_runs in JSON)"
else
  echo "  NUM_RUNS         : (unset – using per-scenario num_runs from JSON)"
fi
echo "  OUTPUT_DIR       : ${OUTPUT_DIR}"
echo ""

python -m validation.veloc.validate \
  "${ORIGINAL_DIR}" \
  "${RESILIENT_DIR}" \
  --executable-name ExaMiniMD \
  --num-procs "${NUM_PROCS}" \
  --original-args "${COMMON_ARGS}" \
  --resilient-args "${COMMON_ARGS}" \
  --output-dir "${OUTPUT_DIR}" \
  --comparison-method custom \
  --custom-comparator "${CUSTOM_COMPARATOR}" \
  --output-file-name stdout.txt \
  --max-attempts 10 \
  --injection-delay 2.0 \
  --install-resilient \
  --veloc-config-name veloc.cfg \
  --benchmark-config "${BENCHMARK_CONFIG}" \
  ${NUM_RUNS_FLAG} \
  ${RESUME_FLAG} \
  "$@"
