#!/usr/bin/env bash
# Run the full VeloC validation pipeline for Quicksilver vs resilient_Quicksilver.
#
# Baseline (original):  build/ecp/Quicksilver  (BUILD_DIR sandbox copy)
# Resilient:            build/ecp_output/resilient_Quicksilver
#
# Usage (from repo root):
#   ./validation/veloc/run_quicksilver_validation.sh [--skip-benchmarks] [--skip-report]
#
# Optional environment variables:
#   ORIGINAL_DIR   – path to the original Quicksilver codebase
#                    (default: build/ecp/Quicksilver — BUILD_DIR sandbox copy)
#   RESILIENT_DIR  – path to the resilient codebase generated by agents/veloc
#                    (default: build/ecp_output/resilient_Quicksilver)
#   INPUT_FILE     – path to the Quicksilver .inp input file
#                    (default: build/ecp/Quicksilver/Examples/ValidationMixed/validationMixed.inp)
#                    (exported so benchmark JSON config can expand ${INPUT_FILE:-...})
#   NUM_PROCS      – number of MPI ranks             (default: 4)
#   OUTPUT_DIR     – validation output directory     (default: build/validation_output/quicksilver)
#   NUM_RUNS       – override benchmark repetitions for ALL scenarios (unset by default;
#                    when unset, each scenario uses its own num_runs from the JSON config;
#                    set to 1 for a quick smoke-test: NUM_RUNS=1 ./run_quicksilver_validation.sh)
#
# Benchmark scenarios are defined in:
#   validation/veloc/benchmark_configs/quicksilver.json
# Each scenario specifies its own num_runs, num_procs, app_args, and failure injection settings.
# NUM_RUNS (if set) takes priority over per-scenario num_runs in the JSON.
#
# Comparison method:
#   Custom plugin: validation/veloc/quicksilver_comparator.py
#   Parses per-cycle balance tally table from stdout.txt and compares the 12
#   deterministic integer columns (start, source, rr, split, absorb, scatter,
#   fission, produce, collisn, escape, census, num_seg) exactly.
#   Timing columns (scalar_flux, cycleInit, cycleTracking, cycleFinalize) are ignored.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Activate virtualenv if available (created by ./setup.sh).
if [[ -d "build/venv" ]]; then
  # shellcheck disable=SC1091
  source "build/venv/bin/activate"

  # Ensure validation Python dependencies are installed (matplotlib, numpy, etc.)
  REQS="${REPO_ROOT}/validation/requirements.txt"
  if [[ -f "${REQS}" ]]; then
    pip install -q -r "${REQS}"
  fi
fi

export PYTHONPATH="${REPO_ROOT}:${PYTHONPATH:-}"

# ---------------------------------------------------------------------------
# Configurable paths and parameters
# ---------------------------------------------------------------------------
ORIGINAL_DIR="${ORIGINAL_DIR:-${REPO_ROOT}/build/ecp/Quicksilver}"
RESILIENT_DIR="${RESILIENT_DIR:-${REPO_ROOT}/build/ecp_output/resilient_Quicksilver}"
# Export INPUT_FILE so the benchmark JSON config can expand ${INPUT_FILE:-...} via os.environ.
# Use the BUILD_DIR sandbox copy so we never modify the source tree.
# setup.sh copies tests/ecp/vanillas/* → build/ecp/*.
export INPUT_FILE="${INPUT_FILE:-${REPO_ROOT}/build/ecp/Quicksilver/Examples/ValidationMixed/validationMixed.inp}"
NUM_PROCS="${NUM_PROCS:-2}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/build/validation_output/quicksilver}"

BENCHMARK_CONFIG="${REPO_ROOT}/validation/veloc/benchmark_configs/quicksilver.json"
CUSTOM_COMPARATOR="${REPO_ROOT}/validation/veloc/quicksilver_comparator.py"

# Quicksilver CLI arguments:
#   -i <input_file>        Input .inp file
#                          validationMixed.inp: nGroups=1, nParticles=100000, nSteps=20,
#                          90% scattering / 10% absorption, 10x10x10 mesh.
#                          Runs in ~6s with 4 MPI ranks — long enough for failure injection.
#
# NOTE: Quicksilver reads the input file AFTER CLI args, so CLI overrides for
#       nSteps/nParticles are silently overwritten by the input file values.
#       All workload parameters must be set in the input file itself.
#
# NOTE: Domain decomposition is left to Quicksilver auto-detect (xDom=0 yDom=0 zDom=0
#       in input file). Explicit --xDom/--yDom/--zDom overrides cause segfaults.
COMMON_ARGS="-i ${INPUT_FILE}"

STATE_FILE="${OUTPUT_DIR}/pipeline_state.json"

# ---------------------------------------------------------------------------
# Detect incomplete previous run and ask user what to do
# ---------------------------------------------------------------------------
RESUME_FLAG=""

if [[ -f "${STATE_FILE}" ]]; then
  # Check if the run is already finished (has "finished": true in the JSON).
  if python3 -c "
import json, sys
state = json.load(open('${STATE_FILE}'))
sys.exit(0 if state.get('finished') else 1)
" 2>/dev/null; then
    echo ""
    echo "============================================================"
    echo "  A previous validation run in:"
    echo "    ${OUTPUT_DIR}"
    echo "  completed successfully."
    echo "============================================================"
    echo ""
    echo "Options:"
    echo "  [1] Re-run graphical report only  (skip correctness + benchmarks)"
    echo "  [2] Start a fresh run             (deletes previous output)"
    echo "  [3] Exit (keep previous results)"
    echo ""
    read -rp "Your choice [1/2/3]: " CHOICE
    case "${CHOICE}" in
      1)
        echo "[run] Re-running graphical report stage only..."
        RESUME_FLAG="--resume --skip-correctness --skip-benchmarks"
        # Clear the 'report' stage from state so validate.py will re-run it.
        python3 -c "
import json
p = '${STATE_FILE}'
state = json.load(open(p))
state['completed_stages'] = [s for s in state.get('completed_stages', []) if s != 'report']
state['finished'] = False
json.dump(state, open(p, 'w'), indent=2)
"
        ;;
      2)
        echo "[run] Removing previous output directory: ${OUTPUT_DIR}"
        rm -rf "${OUTPUT_DIR}"
        ;;
      *)
        echo "[run] Exiting. Previous results are preserved in ${OUTPUT_DIR}"
        exit 0
        ;;
    esac
  else
    # Incomplete previous run found.
    COMPLETED=$(python3 -c "
import json, sys
try:
    state = json.load(open('${STATE_FILE}'))
    stages = state.get('completed_stages', [])
    print(', '.join(stages) if stages else '(none)')
except Exception:
    print('(unknown)')
" 2>/dev/null || echo "(unknown)")

    LAST_UPDATED=$(python3 -c "
import json, sys
try:
    state = json.load(open('${STATE_FILE}'))
    print(state.get('last_updated') or state.get('started_at') or '(unknown)')
except Exception:
    print('(unknown)')
" 2>/dev/null || echo "(unknown)")

    echo ""
    echo "============================================================"
    echo "  An INCOMPLETE previous validation run was found in:"
    echo "    ${OUTPUT_DIR}"
    echo "  Last updated : ${LAST_UPDATED}"
    echo "  Completed    : ${COMPLETED}"
    echo "============================================================"
    echo ""
    echo "Options:"
    echo "  [1] Resume from last completed stage"
    echo "  [2] Start a completely fresh run  (deletes previous output)"
    echo "  [3] Exit (do nothing)"
    echo ""
    read -rp "Your choice [1/2/3]: " CHOICE
    case "${CHOICE}" in
      1)
        echo "[run] Resuming previous run..."
        RESUME_FLAG="--resume"
        ;;
      2)
        echo "[run] Removing previous output directory: ${OUTPUT_DIR}"
        rm -rf "${OUTPUT_DIR}"
        ;;
      3)
        echo "[run] Exiting. Previous run is preserved in ${OUTPUT_DIR}"
        exit 0
        ;;
      *)
        echo "[run] Invalid choice. Exiting."
        exit 1
        ;;
    esac
  fi
fi

# ---------------------------------------------------------------------------
# Build optional --benchmark-num-runs flag (only when NUM_RUNS is set).
# When NUM_RUNS is set it overrides per-scenario num_runs in the JSON config.
# When NUM_RUNS is unset, per-scenario num_runs from the JSON is used.
# ---------------------------------------------------------------------------
NUM_RUNS_FLAG=""
if [[ -n "${NUM_RUNS:-}" ]]; then
  NUM_RUNS_FLAG="--benchmark-num-runs ${NUM_RUNS}"
fi

# ---------------------------------------------------------------------------
# Run the validation framework
# ---------------------------------------------------------------------------
echo ""
echo "[run] Configuration:"
echo "  ORIGINAL_DIR     : ${ORIGINAL_DIR}"
echo "  RESILIENT_DIR    : ${RESILIENT_DIR}"
echo "  INPUT_FILE       : ${INPUT_FILE}"
echo "  NUM_PROCS        : ${NUM_PROCS}"
echo "  BENCHMARK_CONFIG : ${BENCHMARK_CONFIG}"
echo "  CUSTOM_COMPARATOR: ${CUSTOM_COMPARATOR}"
if [[ -n "${NUM_RUNS:-}" ]]; then
  echo "  NUM_RUNS         : ${NUM_RUNS}  (overrides per-scenario num_runs in JSON)"
else
  echo "  NUM_RUNS         : (unset – using per-scenario num_runs from JSON)"
fi
echo "  OUTPUT_DIR       : ${OUTPUT_DIR}"
echo ""

python -m validation.veloc.validate \
  "${ORIGINAL_DIR}" \
  "${RESILIENT_DIR}" \
  --executable-name qs \
  --num-procs "${NUM_PROCS}" \
  --original-args "${COMMON_ARGS}" \
  --resilient-args "${COMMON_ARGS}" \
  --output-dir "${OUTPUT_DIR}" \
  --comparison-method custom \
  --custom-comparator "${CUSTOM_COMPARATOR}" \
  --output-file-name stdout.txt \
  --max-attempts 10 \
  --injection-delay 6.0 \
  --install-resilient \
  --veloc-config-name veloc.cfg \
  --benchmark-config "${BENCHMARK_CONFIG}" \
  ${NUM_RUNS_FLAG} \
  ${RESUME_FLAG} \
  "$@"
